FROM zerolinck/passiflora-server-builder AS build
COPY passiflora-server /app
WORKDIR /app
RUN ./gradlew :passiflora-gateway-app:build -x test -Denv=dev

FROM openjdk:21-jdk
ARG JAR_FILE=passiflora-gateway-*.jar
COPY --from=build /app/passiflora-gateway-app/build/libs/${JAR_FILE} /app/app.jar
WORKDIR /app
VOLUME /etc/localtime:/etc/localtime:ro
EXPOSE 51000
ENTRYPOINT java $JAVA_OPTS -jar app.jar