FROM zerolinck/passiflora-server-builder AS build
COPY passiflora-server /app
WORKDIR /app
RUN ./gradlew :passiflora-iam-app:build -x test -Denv=local

FROM openjdk:21-jdk
ARG JAR_FILE=passiflora-iam-*.jar
COPY --from=build /app/passiflora-iam-app/build/libs/${JAR_FILE} /app/app.jar
WORKDIR /app
VOLUME /etc/localtime:/etc/localtime:ro
EXPOSE 51001
ENTRYPOINT java $JAVA_OPTS -jar app.jar